/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.Timezone;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.time.LocalTime;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author elisc
 */
public class UhrzeitGUI extends javax.swing.JFrame {

    /**
     * Creates new form UhrzeitGUI
     */
    public UhrzeitGUI() {
        initComponents();
        this.setSize(700, 400);
        this.setLayout(new GridLayout(3, 2, 3, 3));
        init();
    }

    public void init() {
        LocalTime now = LocalTime.now();
        JLabel localLabel = new JLabel();
        localLabel.setHorizontalAlignment(SwingConstants.CENTER);
        localLabel.setFont(new Font("", Font.BOLD, 18));
        localLabel.setForeground(Color.WHITE);
        localLabel.setBackground(Color.BLACK);
        localLabel.setOpaque(true);

        JLabel region1Label = new JLabel();
        region1Label.setHorizontalAlignment(SwingConstants.CENTER);
        region1Label.setFont(new Font("", Font.BOLD, 18));
        region1Label.setForeground(Color.WHITE);
        region1Label.setBackground(Color.BLACK);
        region1Label.setOpaque(true);

        JLabel region2Label = new JLabel();
        region2Label.setHorizontalAlignment(SwingConstants.CENTER);
        region2Label.setFont(new Font("", Font.BOLD, 18));
        region2Label.setForeground(Color.WHITE);
        region2Label.setBackground(Color.BLACK);
        region2Label.setOpaque(true);

        Timezone tzLocal = new Timezone(now);

        String region1 = JOptionPane
                .showInputDialog("Bitte Region für die erste zusätzliche Zeitzone angeben: ");
        long verschiebung1 = Long
                .parseLong(JOptionPane
                        .showInputDialog("Bitte Zeitverschiebung in Stunden für die erste zusätzliche Zeitzone angeben: "));
        Timezone tzDistant1 = new Timezone(now.plusHours(verschiebung1));

        String region2 = JOptionPane
                .showInputDialog("Bitte Region für die zweite zusätzliche Zeitzone angeben: ");
        long verschiebung2 = Long
                .parseLong(JOptionPane
                        .showInputDialog("Bitte Zeitverschiebung in Stunden für die zweite zusätzliche Zeitzone angeben: "));
        Timezone tzDistant2 = new Timezone(now.plusHours(verschiebung2));

        new Thread(tzLocal).start();
        new Thread(tzDistant1).start();
        new Thread(tzDistant2).start();

        localLabel.setText("Lokale Zeitzone");
        region1Label.setText(region1);
        region2Label.setText(region2);

        this.add(localLabel);
        this.add(tzLocal);
        this.add(region1Label);
        this.add(tzDistant1);
        this.add(region2Label);
        this.add(tzDistant2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UhrzeitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UhrzeitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UhrzeitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UhrzeitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UhrzeitGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
